---
- hosts: debian
  become: yes
  gather_facts: yes
  tasks:
    - name: Update packages
      apt:
        state: latest
        update_cache: yes
        upgrade: full
        autoclean: yes
        autoremove: yes