---
- hosts: debian
  become: yes
  gather_facts: yes
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        state: latest
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        clean: yes