---
- hosts: fedora
  become: yes
  gather_facts: yes
  tasks:
    - name: Update packages
    ansible.builtin.dnf:
        name: "*"
        state: latest
        allowerasing: true
        update_cache: true
